[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']
[[plugins]]
repo = 'andviro/flake8-vim'
on_ft = ['python']
[[plugins]]
repo = 'tell-k/vim-autopep8'
on_ft = ['python']

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['md']

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = ['tf']

[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
onf_ft=['dart']
[[plugins]]
repo = 'thosakwe/vim-flutter'
onf_ft=['dart']
