[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']
[[plugins]]
repo = 'andviro/flake8-vim'
on_ft = ['python']
[[plugins]]
repo = 'tell-k/vim-autopep8'
on_ft = ['python']

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['md']


